Restaurant/urls.py
from django.contrib import admin
from django.urls import path, include
from meals import urls as meals_url
from reservation import urls as reserve_url
from blog import urls as blog_url
from aboutus import urls as aboutus_url
from contactus import urls as contactus_url
from menu import urls as menu_url
from home import urls as home_url
from user import urls as user_url

from Restaurant import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('meals/', include(meals_url), name = 'meals'),
    path('reservation/', include(reserve_url), name='reservation'),
    path('blog/', include(blog_url), name='blog'),
    path('aboutus/', include(aboutus_url), name='aboutus'),
    path('contactus/', include(contactus_url), name='contactus'),
    path('menu/', include(menu_url), name='menu'),
    path('user/', include(user_url), name='user'),
    path('', include(home_url), name='home'),

]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [

    path('', views.post_list, name = 'post_list'),
    path('post/', views.post, name='post'),

    path('<int:id>', views.post_detail, name = 'post_detail'),
    path('tags=<slug:tag>', views.post_by_tag, name='post_by_tag'),

    path('category=<slug:category>', views.post_by_category, name='post_by_category'),

]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [

    path('', views.home, name = 'home'),

]

meals/urls.py
from django.urls import path
from . import views

app_name = 'meals'

urlpatterns = [

    path('', views.meal_list, name = 'meal_list'),
    path('<slug:slug>', views.meal_detail, name = 'meal_detail'),


]

menu/urls.py
from django.urls import path
from . import views

app_name = 'menu'

urlpatterns = [

    path('', views.menu_list, name = 'menu_list'),
    path('<slug:slug>', views.meal_detail, name='meal_detail'),

]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render
from meals.models import Meals, Category
from blog.models import Post
from aboutus.models import WhyUs
# Create your views here.

def home(request):

    meals = Meals.objects.all()
    meal_list = Meals.objects.all()
    categories = Category.objects.all()
    posts = Post.objects.all()
    latest_post = Post.objects.last()
    whyus = WhyUs.objects.all()


    context = {
        'meals':meals,
        'meal_list' :meal_list,
        'categories':categories,
        'posts':posts,
        'latest_post':latest_post,
        'whyus':whyus
    }

    return render(request, 'home/index.html', context)

templates/home/index.html
{% extends 'base.html' %}

{% load staticfiles %}
{% block title %}
<title>Home</title>

{% endblock %}

{% block body %}

      <div class="main-wrap">
        <div class="cover_1">
          <div class="img_bg" style="background-image: url({% static 'img/img_rest.jpg' %});" data-stellar-background-ratio="0.5">
            <div class="container">
              <div class="row align-items-center">
                <div class="col-md-12" data-aos="fade-up">
                  <h2 class="heading">Have a Good Time!</h2>
                  <p class="lead">The pleasure of varieties on your plate!! Enjoy Your Meal!!!</p>                </div>
              </div>
            </div>
          </div>
        </div> <!-- .cover_1 -->

        <div class="section services-section">
          <div class="container">

            <div class="row">
              <div class="col-md-6 col-lg-3" data-aos="fade-up">
                <div class="media feature-icon d-block text-center">
                  <div class="icon">
                    <span class="flaticon-soup"></span>
                  </div>
                  <div class="media-body">
                    <h3>Quality Food</h3>
                  </div>
                </div>
              </div>
              <div class="col-md-6 col-lg-3" data-aos="fade-up" data-aos-delay="100">
                <div class="media feature-icon d-block text-center">
                  <div class="icon">
                    <span class="flaticon-vegetables"></span>
                  </div>
                  <div class="media-body">
                    <h3>Fresh Food</h3>
                  </div>
                </div>
              </div>
              <div class="col-md-6 col-lg-3" data-aos="fade-up" data-aos-delay="300">
                <div class="media feature-icon d-block text-center">
                  <div class="icon">
                    <span class="flaticon-pancake"></span>
                  </div>
                  <div class="media-body">
                    <h3>Friendly Staff</h3>
                  </div>
                </div>
              </div>
              <div class="col-md-6 col-lg-3" data-aos="fade-up" data-aos-delay="500">
                <div class="media feature-icon d-block text-center">
                  <div class="icon">
                    <span class="flaticon-tray"></span>
                  </div>
                  <div class="media-body">
                    <h3>Easy Reservation</h3>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div> <!-- .section -->

        <div class="section">
          <div class="container">
            <div class="row justify-content-center">
              <div class="col-md-7 text-center"  data-aos="fade-up">
                <h2 class="mb-4">Our Specialties</h2>
              </div>
            </div>
          </div>
        </div> <!-- .section -->

        <div class="section pt-0 pb-0">

          <div class="menus d-flex bg-light">
            {% for meal in meals %}

            <div class="d-flex item">
              <div class="image" style="background-image: url({{meal.image.url}});" data-aos="fade"></div>
              <div class="text">
                <h3>{{meal.name}}</h3>
                <p>{{meal.description|truncatewords:10}}</p>
                <p class="price">RS {{meal.price}}</p>
              </div>
            </div> <!-- .item -->
            {% endfor %}
          </div>
        </div> <!-- .section -->


        <div class="site-half-wrap d-block d-lg-flex">
          <div class="block-half" data-aos="fade">
            <div class="image-bg-fullwidth" style="background-image: url(img/img_1.jpg);"></div>
            <div class="half d-block d-lg-flex">
              <div class="text">
                <h2 class="mb-4">Feature Menu</h2>
                <p class="mb-4">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eveniet eos quasi, necessitatibus dicta. Temporibus odit sed quisquam commodi, in aut, repellendus porro saepe minus, enim obcaecati fugiat optio eaque odio?</p>
                <p><a href="{% url 'menu:menu_list' %}" class="btn btn-primary btn-outline-primary">View All Menu</a></p>
              </div>
              <div class="image" style="background-image: url(img/img_2.jpg);"></div>
            </div>
          </div>
          <div class="block-half"  data-aos="fade">
            <div class="half d-block d-lg-flex">
              <div class="text">
                <h2 class="mb-4">Master Chef</h2>
                <p class="mb-4">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eveniet eos quasi, necessitatibus dicta. Temporibus odit sed quisquam commodi, in aut, repellendus porro saepe minus, enim obcaecati fugiat optio eaque odio?</p><p><a href="#" class="btn btn-primary btn-outline-primary">Meet Our chef</a></p>
              </div>
              <div class="image" style="background-image: url(img/chef_1.jpg);"></div>
            </div>
            <div class="image-bg-fullwidth" style="background-image: url(img/chef_2.jpg);"></div>
          </div>
        </div>

        <div class="section">
          <div class="container">
            <div class="row justify-content-center">
              <div class="col-md-8" data-aos="fade-up">

                <h2 class="mb-5 text-center">Menu List with Price</h2>

                <ul class="nav site-tab-nav" id="pills-tab" role="tablist">

                  {% for cat in categories %}
                  <li class="nav-item">
                    <a class="nav-link" id="{{cat}}-tab" data-toggle="pill" href="#{{cat}}" role="tab" aria-controls="{{cat}}" aria-selected="true">{{cat}}</a>
                  </li>
                  {% endfor %}

                </ul>
                <div class="tab-content" id="pills-tabContent">
                  {% for cat in categories %}
                  <div class="tab-pane fade show" id="{{cat}}" role="tabpanel" aria-labelledby="{{cat}}-tab">

                    {% for meal in meal_list %}
                      {% if  meal.category == cat%}
                        <div class="d-block d-md-flex menu-food-item">
                          <div class="text order-1 mb-3">
                            <h3><a href="{% url 'meals:meal_detail' meal.slug %}">{{ meal.name }}</a></h3>
                            <p>{{ meal.description|truncatewords:15 }}</p>
                          </div>
                          <div class="price order-2">
                            <strong> Rs {{ meal.price }}</strong>
                          </div>
                        </div> <!-- .menu-food-item -->
                      {% endif %}
                    {% endfor %}


                  </div>
                {% endfor %}
                </div>


              </div>
            </div>
          </div>
        </div>

        <div class="section bg-light">
          <div class="container">
            <div class="row justify-content-center mb-5" data-aos="fade-up">
              <div class="col-md-8  text-center">
                <h2 class="mb-3">Blogs</h2>
              </div>
            </div>
            <div class="row">
              <div class="col-lg-6">

                {% for post in posts %}


                <div class="media d-block d-lg-flex mb-5"  data-aos="fade-up" data-aos-delay="100">
                  {% if image %}
                  <figure class="mr-4 horizontal">
                    <a href="{% url 'blog:post_detail' post.id %}"><img src="{{post.image.url}}" alt="Image placeholder" class="img-fluid"></a>
                  </figure>
                  {% endif %}
                  <div class="media-body">
                    <h3><a href="{% url 'blog:post_detail' post.id %}">{{post.title}}</a></h3>
                    <p class="post-meta"><span><span class="fa fa-calendar"></span> {{post.created}}</span></p>
                    <p>{{post.content|truncatewords:10}}</p>
                    <p><a href="{% url 'blog:post_detail' post.id %}" class="btn btn-primary btn-outline-primary btn-sm">Read More</a></p>
                  </div>
                </div> <!-- .media -->

                {% endfor %}

              </div> <!-- .col-md-6 -->

              <div class="col-lg-6">
                <div class="media d-block mb-5" data-aos="fade-up"  data-aos-delay="400">
                  <figure>
                    <a href="{% url 'blog:post_detail' latest_post.id %}"><img src="{{latest_post.image.url}}" alt="Image placeholder" class="img-fluid"></a>
                  </figure>
                  <div class="media-body">
                    <h3><a href="{% url 'blog:post_detail' latest_post.id %}">{{latest_post.title}}</a></h3>
                    <p class="post-meta"><span><span class="fa fa-calendar"></span>{{latest_post.craeted}}</span></p>
                    <p>{{latest_post.content}}</p>
                    <p><a href="{% url 'blog:post_detail' latest_post.id %}" class="btn btn-primary btn-outline-primary btn-sm">Read More</a></p>
                  </div>
                </div> <!-- .media -->
              </div>
            </div>
          </div>
        </div> <!-- .section -->

        <div class="section">
          <div class="container">
            <div class="row justify-content-center mb-5" data-aos="fade-up">
              <div class="col-md-8  text-center">
                <h2 class="mb-3">Why Choose Us</h2>
              </div>
            </div>
            <div class="row large-gutters">
              <div class="col-md-6"  data-aos="fade-up" data-aos-delay="200">
                <img src="{% static 'img/img_2.jpg' %}" alt="Image placeholder" class="img-fluid rounded">
              </div>
              <div class="col-md-6" data-aos="fade-up" data-aos-delay="300">
                <div class="accordion" id="accordion">
                  {% for info in whyus %}
                  <div class="accordion-item">
                    <h3 class="mb-0">
                      <a class="btn-block p-3" data-toggle="collapse" href="#collapseOne{{info.id}}" role="button" aria-expanded="true" aria-controls="collapseOne"> {{info.title}} <span class="icon"></span></a>
                    </h3>
                    <div id="collapseOne{{info.id}}" class="collapse show" aria-labelledby="headingOne" data-parent="#accordion">
                      <div class="p-3">
                        <p>{{info.content}}</p>
                      </div>
                    </div>
                  </div> <!-- .accordion-item -->

                  {% endfor %}



                </div>
              </div>
            </div>
          </div>
        </div> <!-- .section -->




      </div> <!-- .main-wrap -->



{% endblock %}