Restaurant/urls.py
from django.contrib import admin
from django.urls import path, include
from meals import urls as meals_url
from reservation import urls as reserve_url
from blog import urls as blog_url
from aboutus import urls as aboutus_url
from contactus import urls as contactus_url
from menu import urls as menu_url
from home import urls as home_url
from user import urls as user_url

from Restaurant import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('meals/', include(meals_url), name = 'meals'),
    path('reservation/', include(reserve_url), name='reservation'),
    path('blog/', include(blog_url), name='blog'),
    path('aboutus/', include(aboutus_url), name='aboutus'),
    path('contactus/', include(contactus_url), name='contactus'),
    path('menu/', include(menu_url), name='menu'),
    path('user/', include(user_url), name='user'),
    path('', include(home_url), name='home'),

]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [

    path('', views.post_list, name = 'post_list'),
    path('post/', views.post, name='post'),

    path('<int:id>', views.post_detail, name = 'post_detail'),
    path('tags=<slug:tag>', views.post_by_tag, name='post_by_tag'),

    path('category=<slug:category>', views.post_by_category, name='post_by_category'),

]

blog/models.py
from django.db import models
from django.utils import timezone
# from django.contrib.auth.models import User
from taggit.managers import TaggableManager
from user.models import Custom_user

# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    author = models.ForeignKey(Custom_user, on_delete=models.CASCADE, null=True)
    created = models.DateTimeField(default=timezone.now)
    image = models.ImageField(upload_to='blog/', null=True, blank=True,default='blog/default.jpg')

    category = models.ForeignKey('Category', on_delete=models.SET_NULL, null=True)

    tags = TaggableManager(blank = True)

    class Meta:
        verbose_name = 'Post'
        verbose_name_plural = 'Posts'



    def __str__(self):
        return self.title


class Category(models.Model):
    category_name = models.CharField(max_length=50)

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.category_name



class Comment(models.Model):
    user = models.ForeignKey(Custom_user, on_delete=models.CASCADE, null=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    content = models.TextField(max_length=2000)
    created = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return str(self.post)

blog/forms.py
from django import forms

from .models import Comment, Post

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        exclude = ('author',)

blog/views.py
from django.shortcuts import render, redirect, HttpResponse
from .models import Post,Category, Comment, Post
from taggit.models import Tag
from .forms import CommentForm, PostForm
from django.db.models import Q
from user.models import Custom_user
from django.contrib import messages

# Create your views here.

def post_list(request):
    post_list = Post.objects.all()

    ## search

    search_query =request.GET.get('q')
    if search_query:
        post_list = post_list.filter(
            Q(title__icontains = search_query)|
            Q(title__icontains=search_query)|
            Q(tags__name__icontains = search_query)|
            Q(content__icontains = search_query)

        ).distinct()

    context = {
        'post_list':post_list
    }

    return render(request, 'blog/post_list.html', context)

def post_detail(request, id):
    user = Custom_user.objects.all()
    post_detail = Post.objects.get(id=id)
    categories = Category.objects.all()
    all_tags = Tag.objects.all()
    comments = Comment.objects.filter(post=post_detail)
    comment_form = CommentForm()

    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.user = request.user
            new_comment.post = post_detail
            new_comment.save()


    context = {
        'post_detail':post_detail,
        'categories': categories,
        'all_tags': all_tags,
        'comments':comments,
        'comment_form':comment_form
    }

    return render(request, 'blog/post_detail.html', context)


def post_by_tag(request, tag):
    post_by_tag= Post.objects.filter(tags__name__in=[tag])
    context = {
        'post_list': post_by_tag
    }

    return render(request, 'blog/post_list.html', context)


def post_by_category(request, category):
    post_by_category = Post.objects.filter(category__category_name=category)
    context = {
        'post_list': post_by_category,
    }

    return render(request, 'blog/post_list.html', context)


def post(request):
    # post_detail = Post.objects.get(id=id)
    if request.method == 'GET':
        post = PostForm()
        return render(request, 'blog/post.html', {'form':post})
    else:
        post = PostForm(request.POST, request.FILES)
        new_post = post.save(commit=False)
        new_post.user = request.user
        new_post.post = post_detail
        new_post.save()
        return HttpResponse('Blog posted successfully')
            # messages.success(request, 'Blog posted successfully')
            # return redirect(request, 'home:home')

templates/blog/post.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load staticfiles %}
{% block title %}
<title>Register</title>

{% endblock %}

{% block body %}

      <div class="main-wrap">
        <div class="cover_1">
          <div class="img_bg" style="background-image: url({% static 'img/img_rest.jpg' %});" data-stellar-background-ratio="0.5">
            <div class="container">
              <div class="row align-items-center">
                <div class="col-md-12" data-aos="fade-up">
                  <h2 class="heading">Post your Blog</h2>
                </div>
              </div>
            </div>
          </div>
        </div> <!-- .cover_1 -->
          <br>
          <div class="container">
              <form action="" method="POST" enctype="multipart/form-data">
                  {% csrf_token %}
                    {% bootstrap_form form %}
                        {% buttons %}
                            <button type="submit" class="btn btn-primary">Post</button>
                        {% endbuttons %}
                </form>

          </div>



      </div> <!-- .main-wrap -->



{% endblock %}

templates/blog/post_detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load bootstrap4 %}

{% block title %}
<title>Blog Details</title>

{% endblock %}
{% block body %}

  <div class="main-wrap">
        <div class="cover_1 cover_sm">
          <div class="img_bg" style="background-image: url({% static 'img/img_rest.jpg' %});" data-stellar-background-ratio="0.5">
            <div class="container">
              <div class="row align-items-center justify-content-center">
                <div class="col-md-7 text-center" data-aos="fade-up">
                  <h2 class="heading mb-4">{{ post_detail }}</h2>

                  <div class="post-info">
                    <div class="date-info">{{post_detail.created}}</div>
                    <div class="category-info"><span class="seperator">|</span>In <a href="#" data-title="View all posts in Lifestyle" title="View all posts in Lifestyle">Lifestyle</a></div>
                    <div class="author-info"><span class="seperator">|</span>By <a href="#">{{post_detail.author}}</a></div>
                  </div>

                </div>
              </div>
            </div>
          </div>
        </div> <!-- .cover_1 -->

       <div class="section">
          <div class="container">

            <div class="row">

              <div class="col-md-8">
                   <figure>
                    <a href="blog-single.html"><img src="{{post_detail.image.url}}" alt="Image placeholder" class="img-fluid"></a>
                  </figure>
                <p>{{post_detail.content}}</p>

                <div class="tag-widget post-tag-container mb-5 mt-5">
                  <div class="tagcloud">
                    {% for tag in post_detail.tags.all %}

                    <a href="{% url 'blog:post_by_tag' tag%}" class="tag-cloud-link">{{tag.name}}</a>

                    {% endfor %}

                  </div>
                </div>


                <div class="pt-5 mt-5">
                  <h3 class="mb-5">Comments</h3>
                  <ul class="comment-list">

                    {% for comment in comments %}

                    <li class="comment">
                      <div class="vcard bio">
<!--                        <img src="img/person_1.jpg" alt="Image placeholder">-->
                      </div>
                      <div class="comment-body">
                        <h3>{{comment.user}}</h3>
                        <div class="meta">{{comment.created}}</div>
                          <p>{{comment.content}}</p>
                        </div>
                    </li>

                    {% endfor %}

                  </ul>
                </div>

                  <!-- END comment-list -->

                  <div class="comment-form-wrap pt-5">
                    <h3 class="mb-5">Leave a comment</h3>
                    <form method="post" class="p-5 bg-light">
                      {% csrf_token %}
                        {% bootstrap_form comment_form %}
                        {% buttons %}
                            <button type="submit" class="btn btn-primary">Leave a Comment</button>
                        {% endbuttons %}

                    </form>
                  </div>

              </div> <!-- .col-md-8 -->
              <div class="col-md-4 sidebar">
                <div class="sidebar-box">
                  <form action="{% url 'blog:post_list' %}" method="get" class="search-form">
                    <div class="form-group">
                      <span class="icon fa fa-search"></span>
                      <input type="text" class="form-control" name="q" value="{{request.GET.q}}" placeholder="Type a keyword and hit enter">
                    </div>
                  </form>
                </div>
                <div class="sidebar-box">
                  <div class="categories">
                    <h3>Categories</h3>
                    {% for cat in categories %}

                    <li><a href="{% url 'blog:post_by_category' cat %}">{{cat}} </a></li>

                    {% endfor %}

                  </div>
                </div>


                <div class="sidebar-box">
                  <h3>Tag Cloud</h3>
                  <div class="tagcloud">

                    {% for tag in all_tags %}

                    <a href="{% url 'blog:post_by_tag' tag %}" class="tag-cloud-link">{{tag}}</a>

                    {% endfor %}

                  </div>
                </div>


              </div>

            </div>


          </div>
        </div> <!-- .section -->



      </div> <!-- .main-wrap -->

{% endblock %}

      

templates/blog/post_list.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
<title>Blogs</title>

{% endblock %}

{% block body %}
  <div class="main-wrap">
        <div class="cover_1 cover_sm">
          <div class="img_bg" style="background-image: url({% static 'img/img_rest.jpg' %});" data-stellar-background-ratio="0.5">
            <div class="container">
              <div class="row align-items-center justify-content-center">
                <div class="col-md-7" data-aos="fade-up">
                  <h2 class="heading">Blog</h2>
                  <p class="lead">The pleasure of varieties on your plate!! Enjoy Your Meal!!!</p>
                </div>
              </div>
            </div>
          </div>
        </div> <!-- .cover_1 -->

       <div class="section">
          <div class="container">

            <div class="row mb-5">
              {% for post in post_list  %}

              <div class="col-md-4">
                <div class="media d-block media-bg-white mb-5" data-aos="fade-up"  data-aos-delay="400">
                  {% if post.image %}
                  <figure>
                    <a href="blog-single.html"><img src="{{post.image.url}}" alt="Image placeholder" class="img-fluid"></a>
                  </figure>
                  {% endif %}
                  <div class="media-body">
                    <h3><a href="{% url 'blog:post_detail' post.id %}">{{post}}</a></h3>
                    <p class="post-meta"><span><span class="fa fa-calendar"></span> {{ post.created}}</span></p>
                    <p class="mb-4">{{post.content|truncatewords:10}}</p>
                    <p><a href="{% url 'blog:post_detail' post.id %}" class="btn btn-primary btn-outline-primary btn-sm">Read More</a></p>
                  </div>
                </div> <!-- .media -->
              </div>
            {% endfor %}

              </div>
                <div class="row md-5 justify-content-center">
              <a href="{% url 'blog:post' %}" class="btn btn-primary btn-outline-primary btn-sm">Write a blog </a>
            </div>



            </div>


        </div> <!-- .section -->



      </div> <!-- .main-wrap -->




{% endblock %}