Restaurant/urls.py
from django.contrib import admin
from django.urls import path, include
from meals import urls as meals_url
from reservation import urls as reserve_url
from blog import urls as blog_url
from aboutus import urls as aboutus_url
from contactus import urls as contactus_url
from menu import urls as menu_url
from home import urls as home_url
from user import urls as user_url

from Restaurant import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('meals/', include(meals_url), name = 'meals'),
    path('reservation/', include(reserve_url), name='reservation'),
    path('blog/', include(blog_url), name='blog'),
    path('aboutus/', include(aboutus_url), name='aboutus'),
    path('contactus/', include(contactus_url), name='contactus'),
    path('menu/', include(menu_url), name='menu'),
    path('user/', include(user_url), name='user'),
    path('', include(home_url), name='home'),

]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

aboutus/urls.py
from django.urls import path
from . import views

app_name = 'aboutus'

urlpatterns = [

    path('', views.aboutus_list, name = 'aboutus'),


]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [

    path('', views.post_list, name = 'post_list'),
    path('post/', views.post, name='post'),

    path('<int:id>', views.post_detail, name = 'post_detail'),
    path('tags=<slug:tag>', views.post_by_tag, name='post_by_tag'),

    path('category=<slug:category>', views.post_by_category, name='post_by_category'),

]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [

    path('', views.home, name = 'home'),

]

menu/urls.py
from django.urls import path
from . import views

app_name = 'menu'

urlpatterns = [

    path('', views.menu_list, name = 'menu_list'),
    path('<slug:slug>', views.meal_detail, name='meal_detail'),

]

user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [

    path('register/', views.register, name = 'register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),

]

templates/base.html
<!doctype html>
{% load staticfiles %}
<html lang="en">
  <head>
      {% block title %}



      {% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:300,400,700,800|Open+Sans:300,400,700" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">

    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'css/aos.css' %}">

    <link rel="stylesheet" href="{% static 'css/bootstrap-datepicker.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery.timepicker.css' %}">

    <link rel="stylesheet" href="{% static 'fonts/ionicons/css/ionicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/fontawesome/css/font-awesome.min.css' %}">

    <link rel="stylesheet" href="{% static 'fonts/flaticon/font/flaticon.css' %}">

    <!-- Theme Style -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
  </head>
  <body>
    

    <div class="site-wrap">
      
      <nav class="site-menu">
        <div class="site-menu-inner">
          <ul class="list-unstyled">
            <li class="active"><a href="{% url 'home:home' %}">Home</a></li>
            <li><a href="{% url 'menu:menu_list' %}">Our Menu</a></li>
<!--            <li><a href="{% url 'user:login' %}">Login</a></li>-->
            <li><a href="{% url 'blog:post_list' %}">Blogs</a></li>
            <li><a href="{% url 'reservation:reserve_table' %}">Reserve A Table</a></li>
            <li><a href="{% url 'contactus:contactus' %}">Contact Us</a></li>
              <li><a href="{% url 'aboutus:aboutus' %}">About Us</a></li>
              {% if user.is_authenticated %}
                    <li class="nav-item active"><a class="nav-link" href="{% url 'user:logout' %}"> Logout </a></li>
                {% else %}
                    <li class="nav-item active"><a class="nav-link" href="{% url 'user:login' %}"> Login </a></li>
                {% endif %}


          </ul>
        </div>
      </nav>

      <header class="site-header">
        <div class="row align-items-center">
          <div class="col-5 col-md-3">
          </div>

          <div class="col-7 col-md-3 text-right menu-burger-wrap">
            <a href="#" class="site-nav-toggle js-site-nav-toggle"><i></i></a>

          </div>
        </div>
       
      </header> <!-- site-header -->


      
       {% block body %}


      {% endblock %}

      <footer>
        <div class="site-footer">
          <div class="container">
            <div class="row small-gutters mb-5">
              <div class="col-md-6 col-lg-3 mb-5" data-aos="fade" data-aos-delay="100">
                <div class="footer-widget">
                  <h3>Service First</h3>
                  <p>We speak the good food language</p>
                </div>
              </div>
              <div class="col-md-6 col-lg-3 mb-5" data-aos="fade" data-aos-delay="200">
                <div class="footer-widget">
                  <h3>Lunch Service</h3>
                  <p>Booking from 12:00pm - 1:30pm</p>
                  <h3>Service</h3>
                  <p>Everyday: <br> Booking from 6:00pm - 9:00pm</p>
                </div>
              </div>

            </div>
          </div>
          
        </div>
      </footer>

      <div class="site-footer-copyright">
        <div class="container">
          <div class="row">

             <p class="footer-text col-md-12"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
          </div>
        </div>
      </div>

    </div>

    <!-- loader -->
    <div id="loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#f4b214"/></svg></div>

    <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'js/jquery-migrate-3.0.1.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/jquery.waypoints.min.js' %}"></script>

    <script src="{% static 'js/bootstrap-datepicker.js' %}"></script>
    <script src="{% static 'js/jquery.timepicker.min.js' %}"></script>
    <script src="{% static 'js/jquery.stellar.min.js' %}"></script>

    <script src="{% static 'js/aos.js' %}"></script>
    

    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>

    <script src="{% static 'js/main.js' %}"></script>
  </body>
</html>